# Generated by Django 5.0.13 on 2025-05-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conversion_table',
        ),
        migrations.RemoveField(
            model_name='post',
            name='encoded_caption',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
