# Generated by Django 5.0.13 on 2025-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_conversion_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Mobiles', 'Mobiles'), ('Vehicles', 'Vehicles'), ('Property For Sale', 'Property For Sale'), ('Property For Rent', 'Property For Rent'), ('Electronics & Home Appliances', 'Electronics & Home Appliances'), ('Bikes', 'Bikes'), ('Business, Industrial & Agriculture', 'Business, Industrial & Agriculture'), ('Animals', 'Animals'), ('Furniture & Home Decor', 'Furniture & Home Decor'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Books, Sports & Hobbies', 'Books, Sports & Hobbies'), ('Kids', 'Kids'), ('Services', 'Services'), ('Jobs', 'Jobs')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
