# Generated by Django 5.0.13 on 2025-05-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
