# Generated by Django 5.0.13 on 2025-05-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_likepost_username_likepost_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='user_id',
            new_name='user',
        ),
    ]
