# Generated by Django 5.0.13 on 2025-05-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
    ]
